version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "database"
    restart: unless-stopped
    volumes:
      - nx-postgres:/var/lib/postgresql/data/
    networks:
      - nx-network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: "passwd"
    restart: unless-stopped
    volumes:
      - nx-redis:/data
    networks:
      - nx-network

  backend:
    image: nx-monorepo/backend:alpha
    container_name: backend
    ports:
      - "3333:3333"
    environment:
      APP_NAME: NX-powered Applications
    restart: unless-stopped
    networks:
      - nx-network

  frontend:
    image: nx-monorepo/frontend:alpha
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:3333/api
    restart: unless-stopped
    networks:
      - nx-network

networks:
  nx-network:
    name: nx-network
    driver: bridge

volumes:
  nx-node:
    name: nx-node
  nx-postgres:
    name: nx-postgres
  nx-redis:
    name: nx-redis
