version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "database"
    restart: unless-stopped
    volumes:
      - nx-postgres:/var/lib/postgresql/data/
    networks:
      - nx-network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: "passwd"
    restart: unless-stopped
    volumes:
      - nx-redis:/data
    networks:
      - nx-network

  backend:
    image: backend:dev
    container_name: backend
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
      target: dev
    ports:
      - "3333:3333"
    environment:
      APP_NAME: NX-powered Applications
    restart: unless-stopped
    volumes:
      - ./:/home
      - nx-node:/home/node_modules
    networks:
      - nx-network
    depends_on:
      - postgres
      - redis

  frontend:
    image: frontend:dev
    container_name: frontend
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      ORIGIN: localhost:3000
      API_URL: http://backend:3333/api
    restart: unless-stopped
    volumes:
      - ./:/home
      - nx-node:/home/node_modules
    networks:
      - nx-network
    depends_on:
      - postgres
      - redis
      - backend

networks:
  nx-network:
    name: nx-network
    driver: bridge

volumes:
  nx-node:
    name: nx-node
  nx-postgres:
    name: nx-postgres
  nx-redis:
    name: nx-redis
