version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwd"
      POSTGRES_DB: "database"
    restart: unless-stopped
    volumes:
      - nx-postgres:/var/lib/postgresql/data/
    networks:
      - nx-network

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: "passwd"
    restart: unless-stopped
    volumes:
      - nx-redis:/data
    networks:
      - nx-network

  nest:
    image: nx-monorepo/nest:alpha
    container_name: nest
    ports:
      - "3333:3333"
    restart: unless-stopped
    networks:
      - nx-network

  sveltekit:
    image: nx-monorepo/sveltekit:alpha
    container_name: sveltekit
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - nx-network

networks:
  nx-network:
    name: nx-network
    driver: bridge

volumes:
  nx-node:
    name: nx-node
  nx-postgres:
    name: nx-postgres
  nx-redis:
    name: nx-redis
